name: Detect Column Changes and List Changed Files

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    paths:
      - "models/**" # Monitor changes only in the models directory

jobs:
  detect-and-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch full history to ensure proper diff

    - name: Fetch target branch
      run: |
        git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml jsondiff requests

    - name: Detect column changes and list files
      id: detect_changes
      run: |
        python - <<EOF
        import os
        import json
        import yaml
        from jsondiff import diff

        # Paths and setup
        BASE_MODELS_DIR = "models"
        TARGET_BRANCH = os.environ.get("GITHUB_BASE_REF", "main")
        PREVIOUS_MODEL_PATH = "previous_model"
        
        def get_model_columns(file_path):
          if file_path.endswith(".json"):
            with open(file_path, "r") as f:
              data = json.load(f)
          elif file_path.endswith(".yml") or file_path.endswith(".yaml"):
            with open(file_path, "r") as f:
              data = yaml.safe_load(f)
          else:
            raise ValueError(f"Unsupported file type: {file_path}")
          model_columns = {}
    
          # Extracting columns for each model
          if 'models' in data:
            for model in data['models']:
              model_name = model.get('name')
              columns = []
              if 'columns' in model:
                columns = [col.get('name') for col in model['columns'] if 'name' in col]
              model_columns[model_name] = columns
    
          result = set()
          for key, values in model_columns.items():
            for value in values:
              result.add(key+"."+value)
          return result

        # Fetch changed files
        changed_files = os.popen(f'git diff --name-only origin/{TARGET_BRANCH}').read().splitlines()
        print("Changed files:", changed_files)

        dbt_models = [f for f in changed_files if f.startswith(BASE_MODELS_DIR) and (f.endswith(".json") or f.endswith(".yml") or f.endswith(".yaml"))]

        # Detect column changes
        column_changes = {}
        for model in dbt_models:
            file_extension = os.path.splitext(model)[1]
            previous_model_path = f"{PREVIOUS_MODEL_PATH}{file_extension}"

            # Get previous version of the file
            try:
                os.system(f'git show origin/{TARGET_BRANCH}:{model} > {previous_model_path}')

                if os.path.exists(previous_model_path):
                    prev_columns = get_model_columns(previous_model_path)
                    print("prev_columns:", prev_columns)

                    current_columns = get_model_columns(model)
                    print("current_columns:", current_columns)
                    changes = prev_columns - current_columns
                    if changes:
                        column_changes[model] = list(changes)
            except Exception as e:
                print(f"Error processing {model}: {e}")
            finally:
                if os.path.exists(previous_model_path):
                    os.remove(previous_model_path)

        # Save results
        with open('column_changes.json', 'w') as f:
            json.dump(column_changes, f)

    - name: Post detected changes to Alation
      run: |
        python - <<EOF
        import os
        import json
        import requests

        ALATION_API_URL = "https://96cd-136-226-78-111.ngrok-free.app"
        ALATION_API_TOKEN = os.getenv("ALATION_API_TOKEN")

        with open('column_changes.json', 'r') as f:
            column_changes = json.load(f)
        columnsChanged = list()
        headers = {"Authorization": f"Bearer {ALATION_API_TOKEN}"}
        for model, columns in column_changes.items():
          columnsChanged.extend(columns)
        payload = {
                "columns": columnsChanged
        }
        response = requests.post(ALATION_API_URL, headers=headers, json=payload)
        print(response.json())
        EOF  
        
    - name: Comment on pull request
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const columnChanges = JSON.parse(fs.readFileSync('column_changes.json', 'utf8'));

          const columnChangesList = Object.keys(columnChanges).length > 0
            ? `**Column Changes:**\n${Object.entries(columnChanges).map(([model, cols]) => `- **${model}**: ${cols.join(', ')}`).join('\n')}\n`
            : 'No column changes detected.\n';

          github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${columnChangesList}`,
          });
